config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'asdf' => redirect('stuff/stuff.html')
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  
  get 'homepage' => 'pages#home2'
  post 'messages' => 'pages#createMessage'
  
  get 'messages' => 'admin#messages'
  
  get 'houseViewer' => 'pages#houseViewer'
  

end

app/models/option.rb
class Option < ActiveRecord::Base
    mount_uploader :file, OptionUploader
    
    has_many :option_links
    has_many :houses, through: :option_links
    
    has_many :option_selection_records
    has_many :chosen_by, through: :option_selection_records, source: :user
    
    def self.getTypes
       @types = self.all.collect { |x| x.category }.uniq
       return @types
    end
    
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    def index
        @options = Option.all
    end
    
    def show
        @option = Option.find(params[:id])
    end
    
    def new
        @option = Option.new
    end
    
    def create
        @option = Option.new(option_params)
        
        if @option.save
            redirect_to all_options_path
        else
            redirect_to "#"
        end
    end
    
    def edit
        @option = Option.find(params[:id])
    end
    
    def update
        @option = Option.find(params[:id])
        if @option.update(option_params)
            redirect_to all_options_path(@option)
        else
            redirect_to "#"
        end
    end
    
    def destroy
        @option = Option.find(params[:id])
        @option.destroy
        
        redirect_to all_options_path
    end
    
    private
    def option_params
        params.require(:option).permit(:name, :file, :category)
    end
    
    
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/shared/options/_builder_table.html.erb
<table class="table">
    <thead>
        <th>#</th>
        <th>Name</th>
        <th>Category</th>
        <th></th>
        <th></th>
        <th></th>
    </thead>
    
    <tbody>
        <% @row = 1 %>
        <% @options.each do |o| %>
            <tr>
                <th scope="row"><%= @row %></th>
                <td><%= o.name %></td>
                <td><%= o.category %></td>
                <td>
                    <%= link_to o.file.to_s do %>
                        <button type="button" class="btn btn-primary">View</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to edit_option_path(o.id) do %>
                        <button type="button" class="btn btn-info">Edit</button>
                    <% end %>
                </td>
                
            </tr>
            <% @row += 1 %>
        <% end %>
    </tbody>
</table>

app/views/shared/options/_table.html.erb
<table class="table">
    <thead>
        <th>#</th>
        <th>Name</th>
        <th>Category</th>
        <th></th>
        <th></th>
        <th></th>
    </thead>
    
    <tbody>
        <% @row = 1 %>
        <% @options.each do |o| %>
            <tr>
                <th scope="row"><%= @row %></th>
                <td><%= o.name %></td>
                <td><%= o.category %></td>
                <td>
                    <%= link_to o.file.to_s do %>
                        <button type="button" class="btn btn-warning">Download</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to edit_option_path(o.id) do %>
                        <button type="button" class="btn btn-info">Edit</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to option_path(o), method: "delete" do %>
                        <button type="button" class="btn btn-danger">Delete</button>
                    <% end %>
                </td>
            </tr>
            <% @row += 1 %>
        <% end %>
    </tbody>
</table>