config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'asdf' => redirect('stuff/stuff.html')
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'

  get 'create-house' => 'houses#new'
  get '/houses' => 'houses#index'
  resources :houses
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get '/unreal' => 'webplayers#index'
  
  post '/' => 'sessions#create'
  
  get 'dashboard' => 'pages#dashboard'
  
  get 'index' => 'pages#index'
  get '/my-houses' => 'builder#houses'
  get '/my-customers' => 'builder#customers'
  get '/my-customers/:id' => 'builder#customer_info'
  get '/my-options' => 'builder#options'
  
  
  resources :options
  get 'all-users' => 'admin#users'
  get 'all-houses' => 'admin#houses'
  get 'all-options' => 'admin#options'
  
  get 'highscore' => 'unity#highscore'
  get 'highscoreUpdate' => 'unity#highscoreUpdate'
  get 'optionsJSON' => 'unity#optionsJSON'
  
  get 'houseName' => 'unity#houseName'
  get 'houseNameUpdate' => 'unity#houseNameUpdate'
  
  get 'game' => 'pages#game'
  get 'game/index.html' => 'pages#game'
  
  get 'username' => 'unity#username'
  
  get 'gameStarter/:id' => 'unity#gameStarter'
  get 'gameTester' => 'unity#gameTester'
  post 'updateChoices' => 'unity#updateChoices'
  
  get 'gameData' => 'unity#gameData'
  
  get 'communities' => 'builder#communities'
  post 'communities' => 'builder#createCommunity'
  get 'loginStats' => 'pages#loginStats'
  
  
  get 'homepage' => 'pages#home2'
  post 'messages' => 'pages#createMessage'
  
  get 'messages' => 'admin#messages'
  
  get 'houseViewer' => 'pages#houseViewer'
  

end

app/models/community.rb
class Community < ActiveRecord::Base
    has_one :community_builder_link
    has_one :user, through: :community_builder_link
    
    has_many :community_house_links
    has_many :houses, through: :community_house_links
    
    
    
end

app/models/community_buyer_link.rb
class CommunityBuyerLink < ActiveRecord::Base
    belongs_to :community
    belongs_to :buyer, :class_name => 'User'
end

app/models/community_house_link.rb
class CommunityHouseLink < ActiveRecord::Base
    belongs_to :community
    belongs_to :house
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/customer_record.rb
class CustomerRecord < ActiveRecord::Base
    #belongs_to :user
    belongs_to :contractor, :class_name => 'User'
    belongs_to :customer, :class_name => 'User'
    belongs_to :house
    belongs_to :community
end

app/models/house.rb
class House < ActiveRecord::Base
    has_many :house_records
    has_many :users, through: :house_records
    has_many :customer_records
    
    has_many :option_links
    has_many :options, through: :option_links
    
    has_one :community_house_link
    has_one :community, through: :community_house_link
    
    mount_uploader :picture, HousepicUploader
    mount_uploader :file, HousefileUploader
    mount_uploader :meta, HousefileUploader
end

app/models/house_record.rb
class HouseRecord < ActiveRecord::Base
    belongs_to :house
    belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
    mount_uploader :file, OptionUploader
    
    has_many :option_links
    has_many :houses, through: :option_links
    
    has_many :option_selection_records
    has_many :chosen_by, through: :option_selection_records, source: :user
    
    def self.getTypes
       @types = self.all.collect { |x| x.category }.uniq
       return @types
    end
    
end

app/models/option_link.rb
class OptionLink < ActiveRecord::Base
    belongs_to :houses
    belongs_to :option
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :house_records
    has_many :houses, through: :house_records
    
    
    has_many :customer_links, :class_name => "CustomerRecord", :foreign_key => "contractor_id"
    has_many :customers, :through => :customer_links, :source => :customer
    
    has_one :contractor_link, :class_name => "CustomerRecord", :foreign_key => "customer_id"
    has_one :contractor, :through => :contractor_link, :source => :contractor
    
    has_one :assigned_house, :through => :contractor_link, :source => :house
    
    has_many :option_selection_records
    has_many :selected_options, through: :option_selection_records, source: :option
    
    
    
    
    has_many :community_builder_links
    has_many :communities, through: :community_builder_links
    
    
    
    
    
    
    def self.search(query)
        User.where(:first_name, query)
    end
  
    
    has_secure_password
    
    def admin?
        self.role == 'admin'
    end
    
    def buyer?
        self.role == 'buyer'
    end
    
    def builder?
        self.role == 'builder'
    end
    
    def get_pending
        self.houses.where(status: "pending").count
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builder_helper.rb
module BuilderHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/unity_helper.rb
module UnityHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/options.html.erb
<h2>Options</h2>
<hr>

<div class="row">
    <div class='col-md-2 sidebar'>
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" <% if params[:category] == nil %> class="active" <% end %> >
                <a href="?">All Options</a>
            </li>
            <hr>
            <% @categorys.each do |c| %>
                <li role="presentation" <% if params[:category] == c %> class="active" <% end %>>
                    <a href="?category=<%= c %>">
                        <%= c %>
                    </a>
                </li>
            <% end %>
        </ul>
        <hr>
        <%= link_to new_option_path do %>
             <button type="button" class="btn btn-success">New Option</button>
        <% end %>
    </div>
    
    <div class='col-md-10'>
        
        <div class="navbar navbar-default">
          <%#-  http://www.jorgecoca.com/buils-search-form-ruby-rails/  %>
          <%= form_tag(all_options_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Options" %>
              <span class="input-group-btn">
                <button class="btn" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
              </span>
            </div>
          <% end %>
        </div>
        
        <%= render "shared/options/table" %>
        
    </div>
</div>

app/views/admin/users.html.1.erb
<div class="row">
  <div class="col-md-2 sidebar">
    <br>
    <ul class="nav nav-pills nav-stacked">
      
      <br><br><br><br><br><br>
      <li role="presentation"  <% if @filter == "admin" %> class="active" <% end %> >
        <a href="?filter=admin" > Admin </a>
      </li>
      <li role="presentation" <% if @filter == "builder" %> class="active" <% end %>>
        <a href="?filter=builder">Builders</a>
      </li>
      <hr>
      <li role="presentation">
        <%= link_to new_user_path do %>
          <button type="button" class="e360-btn">Add New User</button>
        <% end %>
      </li>
      
    </ul>
    
  </div>
  
  <div class="col-md-9 main">
    <br>
    <div class="navbar navbar-default">
      <%#-  http://www.jorgecoca.com/buils-search-form-ruby-rails/  %>
      <%= form_tag(all_users_path, :method => "get", class: "navbar-form", id: "search-form") do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Users" %>
          <span class="input-group-btn">
            <button class="btn" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </span>
        </div>
      <% end %>
    </div>
    
    <%= render "shared/users_table" %>
    
  </div>
</div>

app/views/admin/users.html.erb
<div class="navbar navbar-default" >
  <div class="row">
    
    <div style="flaot: left" class="col-xs-6">
      <h2 class="e360-page-header">Users</h2>
    </div> 
    
    <div class="col-xs-6">
      <%#-  http://www.jorgecoca.com/buils-search-form-ruby-rails/  %>
      <%= form_tag(all_users_path, :method => "get", class: "navbar-form", style: "float: right", id: "search-form") do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Users" %>
          <span class="input-group-btn">
            <button class="btn" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </span>
        </div>
      <% end %>
    </div>
    
  </div>
</div>


<div class="row">
  <div class="col-md-2 sidebar">
    
    <br>
    <ul class="nav  nav-stacked">
      
      <a href="?filter=admin" style="text-decoration: none;">
        <li  <% if @filter == "admin" %> class="active" <% end %> >
          <div class="e360-sidebar-btn"> Admin</div>
        </li>
      </a>
      
      <a href="?filter=builder" style="text-decoration: none;">
        <li role="presentation" <% if @filter == "builder" %> class="active" <% end %>>
          <div class="e360-sidebar-btn">Builders</div>
        </li>
      </a>
      
      <hr>
      <li role="presentation">
        <%= link_to new_user_path do %>
          <button type="button" class="e360-btn">Add New User</button>
        <% end %>
      </li>
      
    </ul>
    
  </div>
  
  <div class="col-md-9 col-md-offset-1 main">
    
    
    <%= render "shared/users_table" %>
    
  </div>
</div>

app/views/pages/dashboard.html.erb
<h2>Dashboard</h2>
<hr>

<div class="row">
    <% if current_user && current_user.admin? %>
        <div class="col-md-4">
            
            <%= link_to all_users_path do %>
                <button type="button" class="e360-btn e360-btn-lrg e360-btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    All Users
                </button>
            <% end %>
            
            <br>
            
            <%= link_to all_houses_path do %>
                <button type="button" class="e360-btn e360-btn-lrg e360-btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    </div>
                    All Houses
                </button>
            <% end %>
            
            <br>
            <%= link_to all_options_path do %>
                <button type="button" class="e360-btn e360-btn-lrg e360-btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    </div>
                    Options
                </button>
            <% end %>
            
            <br>
            <%= link_to messages_path do %>
                <button type="button" class="e360-btn e360-btn-lrg e360-btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                    </div>
                    Messasges
                </button>
            <% end %>
    </div>
    <% end %>
    
    
    
    
    <% if current_user && current_user.builder? %>
        <div class="col-md-4">
            
            <%= link_to  "/my-houses" do %>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    </div>
                     My Houses
                </button>
            <% end %>
            
            <br>
            
            <%= link_to "/my-customers" do%>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    My Customers
                </button>
            <% end %>
            
            <br>
            <%= link_to communities_path do%>
                <button type="button" class="btn btn-primary btn-lg btn-block">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </div>
                    My Communities
                </button>
            <% end %>
            
        </div>
    <% end %>
    
    
    
    
    <% if current_user && current_user.buyer? %>
        <h1>Welcome, <%= current_user.first_name + " " + current_user.last_name %>!</h1>
        <h3>Your contractor: <%= current_user.contractor.first_name + " " + current_user.contractor.last_name %></h3>
        
        <% if false %>
            <p><a href="http://52.34.11.68/alpha/homes/testhouse4/index.html" class="btn btn-primary" role='button' onclick="window.open('http://52.34.11.68/alpha/homes/testhouse4/index.html', 'newwindow', 'width=1000, height=565'); return false;">Old 3D Viewer</a></p>
            <br>
        <% end %>
        
        <%= link_to "/gameStarter/#{current_user.assigned_house.id.to_s}" do%>
            <button type="button" class="btn btn-primary btn-lg">
                <div class="col-md-1"> 
                    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                </div>
                3D House Viewer
            </button>
        <% end %>
        
        
        <% if false %>
            <%= link_to gameTester_path do%>
                <button type="button" class="btn btn-warning">
                    <div class="col-md-1"> 
                        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                    </div>
                    TextBased Option Selector
                </button>
            <% end %>
        <% end %>
        
     <% end %>
    

app/views/pages/home.html.erb
<script>
$(document).ready(function(){
    $(window).scroll(function() {
        if ($(this).scrollTop() > 15){  
            $('nav.e360-nav').addClass("sticky");
            $('nav.e360-nav').removeClass("e360-nav-home");
            
            $('.e360-logo-banner').animate({
                marginTop: "0",
                top: "0",
                height: "70px",
                paddingLeft: "20px"
            });
            $('.e360-logo-banner').css({
                "position":"fixed",
                "z-index":"999999",
                "background-color" : "rgba(255, 255, 255, 0)"
            });
            
            
        }
    });
    
    $(window).scroll(function() {
        if($(this).scrollTop() < 15) {
            $('nav.e360-nav').removeClass("sticky");
            $('nav.e360-nav').addClass("e360-nav-home");
            
            $('.e360-logo-banner').css({
                "position":"static",
                "background-color" : "rgba(255, 255, 255, 0.46)",
                "marginTop": "300px",
                "height": "180px",
                "paddingLeft": "400px"
                
            });
        }
    });

    
})



</script>

<div class="e360-image-banner" style="background-image: url(<%= asset_path 'kitchen.jpg' %>)">
    <nav class="e360-nav e360-nav-home" >
        <div class="" style="margin-right: 100px">
            <a href="/"><%= image_tag "e360-logo.png", :class => "e360-nav-logo" %></a>
            <ul class="e360-nav-list">
                <li role="presentation" style="float: right"><a href="#" data-toggle="modal" data-target="#myModal"><b>Log In</b></a></li>
                <li role="presentation" style="float: right"><a href="#contactus"><b>Contact Us</b></a></li>
                <li role="presentation" style="float: right"><a href="#about"><b>About</b></a></li>
            </ul>
        </div>
    </nav>
    
    <div class="e360-logo-banner">
        <%= image_tag "e360-logo.png", :class => "" %>
    </div>
    
</div>

<div class="container">
    <div class="e360-row">
        <section class="e360-section" id='about'>
            <div class="e360-section-header">
                <h2>
                    About Us
                    <div class="e360-section-header-highlight"></div>
                </h2>
            </div>
            
            <div class="row">
                <p class="col-md-4">Here at EnvisionIt 360, we have set out to create an experience for the home buyers and contractors alike. We are making it possible for the average American to design their new home on their own time, with out any prior experience. The home owner will also be able to see and </p>
                <p class="col-md-4">manage their budget. Likewise, EnvisionIt 360 will allow contractors to visually see what their customers are wanting and help cut down the time spent in the design center. EnvisionIt 360 will also give contractors analysis to help them better understand their customers </p>
                <p class="col-md-4">and what their customers want in their future home. This will help contractors to tailor their company more effectively to become more profitable and save time and money on different resources.</p>
            </div>
        </section>
    </div>
    
    
    <div class="e360-row">
        <aside class="col-md-4 e360-aside">
            <div></div>
            <h2>PLEASE SEND US A MESSAGE IF YOU ARE INTERESTED IN LEARNING MORE</h2>
            <div></div>
        </aside>
        
        <div class="col-md-8">
            <article class='home-article'>
                <%= form_for (@message = Message.new), html: {class: "form-horizontal"} do |f| %>
                    <div class="form-group" >
                        <label class="col-sm-2 control-label"> Name: </label>
                        <div class="col-sm-10">
                            <%= f.text_field :sender_name, :class => "form-control" %>
                        </div>
                    </div>
                    
                    <div class="form-group" >
                        <label class="col-sm-2 control-label"> Email: </label>
                        <div class="col-sm-10">
                            <%= f.text_field :sender_email, :class => "form-control" %>
                        </div>
                    </div>
                    
                    <div class="form-group" >
                        <label class="col-sm-2 control-label"> Message: </label>
                        <div class="col-sm-10">
                            <%= f.text_area :message_text, size: "50x12", :class => "form-control" %>
                        </div>
                    </div>
                    
                    <div class="form-group" >
                        <div class="col-sm-offset-2 col-sm-10">
                            <%= f.submit "Send", :class => 'e360-btn e360-btn-lrg' %>
                        </div>
                    </div>
                <% end %>
            </article>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        
      <%= form_for(:session, url: login_path) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Log In</h2>
      </div>
      
      <div class="modal-body">
          
        <div class="form-group">
            <%= f.email_field :email, :placeholder => "Email", :class => "form-control" %>
        </div>
            
        <div class="form-group">
            <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
        </div>
        
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Log in", class: 'btn btn-primary' %>
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/pages/home2.html.erb
<link href='https://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<header class="text-center home-header">
    <div class="text-center">
    <span class="logo-text">Envision</span>
    <%= image_tag "EnvisionIt Logo.png" %>
    <span class="logo-text" style="padding-right: 120px">It  360</span>
    </div>
</header>

<div style="background-color: #432c86; display: block; height: 42px"></div>
<section class='' id='about'>
    <div class='home-image-block waterfront'>
        <div class='home-section-title text-center'>
            ABOUT
        </div>
    </div>
    <article class='home-article'>
        <div class='container'>
            <div class="row">
                <div class="col-md-6">
                    Here at EnvisionIt 360, we have set out to create an experience for the home buyers and contractors alike. We are making it possible for the average American to design their new home on their own time, with out any prior experience. The home owner will also be able to see and manage their budget.
                </div>
                
                <div class="col-md-6">
                    Likewise, EnvisionIt 360 will allow contractors to visually see what their customers are wanting and help cut down the time spent in the design center. EnvisionIt 360 will also give contractors analysis to help them better understand their customers and what their customers want in their future home. This will help contractors to tailor their company more effectively to become more profitable and save time and money on different resources.
                </div>
            </div>
            
        </div>
        
    </article>
</section>

<div style="background-color: white; display: block; height: 42px"></div>
<section class='' id='marketing'>
    <div class='home-image-block shingles'>
        <div class='home-section-title text-center'>
            MARKETING
        </div>
    </div>
    <article class='home-article'>
        <div class="container">
           <h3>How It Works</h3>
           <p>
               We take the house plans, all the information about the house, and all the materials that are offered and input online we compile everything and make an enjoyable experience for the home buyer. 
    
           </p>
           <br><br>
           <div class="marketing-image text-center" >
               <%= image_tag 'diagram.png' %>
           </div>
       
        </div>
    </article>
    
</section>
<div style="background-color: white; display: block; height: 42px"></div>
<section class='' id='contactus'>
    <div class='home-image-block phonebooth'>
        <div class='home-section-title text-center'>
            CONTACT US
        </div>
    </div>
    <article class='home-article'>
        <div class="container">
            <div class="row">
                <h3>Please Send us a message if you are interested in learning more:</h3>
                <br>
                <a href="mailto:developers@envitionit360.com">developers@envitionit360.com</a>
            </div>
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            <div class="row">
                <div class='col-md-7'>
                      <%= form_for @message do |f| %>
                          <%= f.text_field :sender_name %>
                          <%= f.text_field :sender_email %>
                          <%= f.text_area :message_text, size: "60x12" %>
                          <%= f.submit "Create" %>
                      <% end %>
                </div>
                
            </div>
        </div>
    </article>
    
</section>

<footer class="home-footer">
    <div class="container text-center">
        EnvisionIt 360 
        
        <br>
        <div class="footer-image" >
            <%= image_tag "EnvisionIt Logo.png" %>
        </div>
        
    </div>
</footer>









<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        
      <%= form_for(:session, url: login_path) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Log In</h2>
      </div>
      
      <div class="modal-body">
          
        <div class="form-group">
            <%= f.email_field :email, :placeholder => "Email", :class => "form-control" %>
        </div>
            
        <div class="form-group">
            <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
        </div>
        
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Log in", class: 'btn btn-primary' %>
      </div>
      <% end %>
      
    </div>
  </div>
</div>
<script>
</script>

app/views/pages/loginStats.html.erb
LOGIN STATS

log

app/views/pages/my_houses.html.erb
<h2>My Houses</h2>
<hr>

<%= render "shared/house_tiles" %>

<hr>
<p>
  <%= link_to new_house_path do %>
    <button type="button" class="btn btn-primary btn-lg">Add New Home</button>
  <% end %>
</p>

app/views/shared/_customers_table.html.erb
<table class="table"> 
    <br>
    <thead> 
        <tr>
            <th>#</th> <th>Name</th> <th>Email</th> <th>Assigned House</th>
        </tr> 
    </thead> 
    <tbody>
        <% @row = 1 %>
        <% @users.each do |u| %>
            
            <tr>
                <th scope="row"><%= @row %></th>
                <td><%= u.first_name + " " + u.last_name %></td>
                <td><%= u.email %></td>
                <td>
                    <%= link_to u.assigned_house do %>
                        <button type="button" class="btn btn-success">House</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to u do %>
                        <button type="button" class="btn btn-primary">View</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to edit_user_path(u.id) do %>
                        <button type="button" class="btn btn-info">Edit</button>
                    <% end %>
                </td>
                
                
            </tr>
            <% @row += 1 %>
            
        <% end %>
        
    </tbody> 
</table>

app/views/shared/_house_table.html.erb
<table class="table"> 
    <br>
    <thead> 
        <tr>
            <th>#</th> <th>House Name</th> <th>Builder</th> <th>Status</th> <th></th> <th></th> <th></th>
        </tr> 
    </thead> 
    <tbody>
        <% @row = 1 %>
        <% @houses.each do |h| %>
            
            <tr>
                <th scope="row"><%= @row %></th>
                <td><%= h.name %></td>
                <td><%= h.users.first.first_name + " " + h.users.first.last_name%></td>
                <td>
                    <% if h.status == "pending" %>
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <% end %>
                    <%= h.status %>
                </td>
                
                <td>
                    <%= link_to h do %>
                        <button type="button" class="btn btn-primary">View</button>
                    <% end %>
                </td>
                
                <td>
                    <%= link_to edit_house_path(h.id) do %>
                        <button type="button" class="btn btn-info">Edit</button>
                    <% end %>
                </td>
                
                <td>
                    <a href="<%= h.file.to_s %>" download>
                        <button type="button" class="btn btn-warning">Download</button>
                    </a>
                </td>
                
            </tr>
            <% @row += 1 %>
            
        <% end %>
        
    </tbody> 
</table>

app/views/shared/_navbar.html.erb
<nav class="e360-nav sticky" >
    <div class="container">
    <a href="/"><%= image_tag "e360-logo.png", :class => "e360-nav-logo" %></a>
    <ul class="e360-nav-list">
      
      
      <!--
      <li role="presentation"><a href="/users">Users</a></li>
      <li role="presentation"><a href="/houses">Houses</a></li>
      -->
      
      
      <% if current_user %>
      
      
            <% if current_user.builder? %>
              <li role="presentation"<% if request.path == my_houses_path %> class="active" <% end %>>
                <%= link_to "Houses", my_houses_path %>
              </li>
              <li role="presentation"<% if request.path == my_customers_path %> class="active" <% end %>>
                <%= link_to "Customers", my_customers_path %>
              </li>
              <li role="presentation"<% if request.path == my_options_path %> class="active" <% end %>>
                <%= link_to "Options", my_options_path %>
              </li>
              
            
            <% end %>  
            <% if current_user.admin? %>
              <li role="presentation"<% if request.path == all_users_path %> class="active" <% end %>>
                <%= link_to "Users", all_users_path %>
              </li>
              <li role="presentation"<% if request.path == all_houses_path %> class="active" <% end %>>
                <%= link_to "Houses", all_houses_path %>
              </li>
              <li role="presentation"<% if request.path == all_options_path %> class="active" <% end %>>
                <%= link_to "Options", all_options_path %>
              </li>
            
            <% end %>
            <% if current_user.buyer? %>
               <li role="presentation"><a href="/"><b><%= current_user.contractor.first_name + " " + current_user.contractor.last_name %></b></a></li>
              
            <% end %>
            
            
            
            
            <li role="presentation" style="float: right"><%= link_to "Log out", logout_path, method: "delete" %></li>
            <li role="presentation" style="float: right"><a href="<%= user_path(current_user) %>"> My Account</a></li>
            
        <% else %>
          
          
          <li role="presentation" style="float: right"><a href="#" data-toggle="modal" data-target="#myModal"> Log In</a></li>
          <li role="presentation" style="float: right"><a href="#contactus"> Contact Us</a></li>
          <li role="presentation" style="float: right"><a href="#marketing"> Marketing</a></li>
          <li role="presentation" style="float: right"><a href="#about"> About</a></li>
          
          
        <% end %>
        
        

    </ul>
    </div>
  </nav>
  <div class="e360-top-spacer"></div>